#!/bin/bash

# Source the configuration file
source config/server-config.sh

# Update the group_vars/all.yml file with the values from server-config.sh
cat > inventory/group_vars/all.yml << EOF
# Cluster configuration
cluster_name: TelecomCluster
cm_admin_user: admin
cm_admin_password: Secure123!
java_version: openjdk-8-jdk

# Server IP configuration
# These values are automatically updated from server-config.sh
master_ip: $MASTER_IP
worker1_ip: $WORKER1_IP
worker2_ip: $WORKER2_IP

# Hostname configuration
master_hostname: $MASTER_HOSTNAME
worker1_hostname: $WORKER1_HOSTNAME
worker2_hostname: $WORKER2_HOSTNAME

# SSH configuration - Master node
master_ssh_user: $MASTER_SSH_USER
master_ssh_password: $MASTER_SSH_PASSWORD

# SSH configuration - Worker nodes
worker1_ssh_user: $WORKER1_SSH_USER
worker1_ssh_password: $WORKER1_SSH_PASSWORD
worker2_ssh_user: $WORKER2_SSH_USER
worker2_ssh_password: $WORKER2_SSH_PASSWORD
EOF

# Generate the inventory file
cat > inventory/hosts.ini << EOF
# This file is automatically generated from the server-config.sh file
# To change server IPs, edit the config/server-config.sh file or run:
# ./scripts/configure-servers.sh

[cloudera_manager]
$MASTER_IP ansible_user=$MASTER_SSH_USER ansible_ssh_pass=$MASTER_SSH_PASSWORD

[master]
$MASTER_IP ansible_user=$MASTER_SSH_USER ansible_ssh_pass=$MASTER_SSH_PASSWORD

[workers]
$WORKER1_IP ansible_user=$WORKER1_SSH_USER ansible_ssh_pass=$WORKER1_SSH_PASSWORD
$WORKER2_IP ansible_user=$WORKER2_SSH_USER ansible_ssh_pass=$WORKER2_SSH_PASSWORD

[all:vars]
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
EOF

echo "Inventory file and group_vars/all.yml updated successfully"
