---
- name: Setup prerequisites for Cloudera
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Java
      apt:
        name: "{{ java_version }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Disable SELinux
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Disable firewall
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - ufw
        - firewalld
      ignore_errors: yes

    - name: Disable swap
      command: swapoff -a
      
    - name: Update fstab to disable swap
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \1'
        
    - name: Set vm.swappiness
      sysctl:
        name: vm.swappiness
        value: '1'
        state: present
        
    - name: Install required packages
      apt:
        name:
          - ntp
          - python3
          - python3-pip
          - wget
          - curl
          - unzip
        state: present
      when: ansible_os_family == "Debian"
