---
- name: Setup prerequisites for Cloudera
  hosts: all
  become: yes
  tasks:
    - name: Check minimum system requirements
      assert:
        that:
          - ansible_memtotal_mb|int >= 16384
          - ansible_processor_vcpus|int >= 4
        msg: "Server does not meet minimum requirements of 16GB RAM and 4 vCPUs"
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Java
      apt:
        name: "{{ java_version }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Disable SELinux
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Disable firewall
      service:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - ufw
        - firewalld
      ignore_errors: yes

    - name: Disable swap
      command: swapoff -a
      
    - name: Update fstab to disable swap
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \1'
        
    - name: Set vm.swappiness
      sysctl:
        name: vm.swappiness
        value: '1'
        state: present
        
    - name: Ensure hostname resolution works
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }} {{ item.hostname }}"
        state: present
      with_items:
        - { ip: "{{ master_ip }}", hostname: "{{ master_hostname }}" }
        - { ip: "{{ worker1_ip }}", hostname: "{{ worker1_hostname }}" }
        - { ip: "{{ worker2_ip }}", hostname: "{{ worker2_hostname }}" }
        
    - name: Install required packages
      apt:
        name:
          - ntp
          - python3
          - python3-pip
          - wget
          - curl
          - unzip
        state: present
      when: ansible_os_family == "Debian"
      
    - name: Create data directories for HDFS
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      with_items:
        - /data
        - /data/dfs
        - /data/dfs/nn
        - /data/dfs/dn
